project_name: trojansourcedetector
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/trojansourcedetector
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md
dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - ghcr.io/haveyoudebuggedit/trojansourcedetector:{{ .Tag }}
      - ghcr.io/haveyoudebuggedit/trojansourcedetector:v{{ .Major }}
      - ghcr.io/haveyoudebuggedit/trojansourcedetector:latest
    extra_files:
      - entrypoint.sh
gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=example.com/blah
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
