FROM alpine

COPY trojansourcedetector /
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /trojansourcedetector /entrypoint.sh

RUN mkdir -p /work
VOLUME /work
WORKDIR /work

ENTRYPOINT ["/trojansourcedetector"]